before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - brian@spreecommerce.com
irc: "irc.freenode.org#spree"
branches:
  only:
    - master
    - 0-7-stable
language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.3
